# on:
#   schedule:
#     # Runs at 01:00 UTC (9:00 AM Beijing) every day
#     - cron:  '0 1 * * *'
on: push
    
name: ESPNET sync
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: espnet/espnet
        dst: hsungong/espnet
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        white_list: "master"
        debug: true

