name: Gitee repos mirror periodic job

on:
  schedule:
  - cron: "0 2 */15 * *"
  push:
    # Sequence of patterns matched against refs/heads
    paths:
      - '.github/workflows/kaldi.yaml'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: kaldi
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: github/kaldi-asr
        dst: gitee/hsungong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: user
        timeout: 600
        debug: true
        white_list: kaldi
        force_update: false
        
        
