name: Gitee repos mirror periodic job

on:
  schedule:
  - cron: "0 2 */2 * *"
  push:
    # Sequence of patterns matched against refs/heads
    paths:
      - '.github/workflows/s3prl.yaml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: s3prl
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: github/s3prl
        dst: gitee/hsungong
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        account_type: user
        timeout: 600
        debug: true
        white_list: s3prl
        force_update: false
        
        
        
